export enum TypeEnum {
  AUTH_CREATE = 'AUTH_CREATE',
  BOARD_CREATE = 'BOARD_CREATE',
  BOARD_VIEW = 'BOARD_VIEW',
  BOARD_LIKE_CREATE = 'BOARD_LIKE_CREATE',
  BOARD_LIKE_REMOVE = 'BOARD_LIKE_REMOVE',
  BOARD_COMMENT_CREATE = 'BOARD_COMMENT_CREATE',
}
